export const announceTestData = [
  {
    "bno" : 1,
    "title" : "여행🛫 & 교육📖 스타트업 소싱 진행 예정 안내",
    "content" : "‘여행 플랫폼과 에듀테크 분야’ 스타트업 발굴을 주제로 PnP DFS(Deal Flow Session)를 개최할 예정입니다.<br> 새로운 소비자 경험창출, AI기반 여행일정 추천, 최적 이동경로안내, 신기술기반 교육 플랫폼 등을 주제로 스타트업 소싱이 진행 될 예정이며 참여를 원하시는 분은 아래의 신청하기를 클릭 해 신청바랍니다.<br />많은 관심 부탁드리겠습니다.<br />일시 : 11월 3주차<br />장소 : 화상 미팅<br />참석자 : 여행 및 교육 플랫폼 관련 스타트업(약 10개)",
    "img" : "1.Travel_Edu_DFS_Notice.png",
    "button" : "Y",
    "link" : ""
  },
  {
    "bno" : 2,
    "title" : "여행🛫 & 교육📖 스타트업 소싱 진행",
    "content" : "11월 17일 ‘여행 플랫폼과 에듀테크 분야’ 스타트업 발굴을 주제로 PnP DFS(Deal Flow Session)를 개최했습니다. <br />이번 DFS에서는 당사(박은호 대표이사, 김문겸 상무)와 그룹사 협의체 임원(토파스 곽진일 대표이사,, 한진관광 안교욱 상무)이 참석하여 스타트업과 시너지 효과를 창출하기 위한 비즈니스 협력방안에 대해 논의하는 자리를 가졌습니다. <br /> 코로나 상황을 고래해 온라인으로 참석한 7개사는 사전 서류심사를 통해 선별된 기업으로, 새로운 소비자 경험창출, AI기반  여행일정 추천, 최적 이동경로안내, 신기술기반 교육 플랫폼 등의 비즈니스 모델을 보유한 스타트업입니다. <br /> 심사 임원분들의 점수에 대한 최종 분석을 마친후 스타트업과 추가적인 논의를 진행할 예정이며 ,미래성장동력 확보와 차세대 기술을 선도하기 위한 오픈이노베이션 활동을 지속해 나갈 예정입니다.",
    "img" : "2.Tour_Edu_DFS.png",
    "button" : "N",
    "link" : ""
  },
  {
    "bno" : 3,
    "title" : "한진, 스타트업과 함께 날아오르다! ✈️",
    "content" : "12월 8일, 한진정보통신은 글로벌 액셀러레이터인 플러그앤플레이(Plug and Play)한국지사에서 처음 주최한 'PnP Batch 0 Expo Demoday'에 참가하여 유니콘기업으로 도약중인 국내 스타트업(물류, 메타버스, AI 분야 등 7개사)과 만남의 시간을 가졌습니다. \n 한진그룹의 오픈이노베이션 전략을 소개한 김문겸상무는'빠르게 변화하는 소비자의 요구사항과 기술의 복잡성 증가로 우수한 서비스와 기술력을 보유한 스타트업과의 협업은 디지털전환 시대에 반드시 필요하다'라고 발표하며 스타트업과의 협력으로 디지털전환 시대에 발빠르게 대비하고 혁신성장하고자 하는 의지를 밝혔습니다. \n 특히 이번 데모데이는 한진그룹 뿐만 아니라 LG, 한화그룹 등 주요 대기업이 참석하여 각 사의 주요사업과 오픈이노베이션에 대해 소개하는 자리를 통해 '오픈이노베이션'이 기업의 새로운 경영전략으로 자리매김하고 있음을 알 수 있는 시간이었습니다.",
    "img" : "3.pnp_demoday.png",
    "button" : "Y",
    "link" : ""
  },
  {
    "bno" : 4,
    "title" : "innoHI 웹페이지 리뉴얼합니다🚧",
    "content" : "그동안 PC에서만 접속되어 많이 불편하셨죠~!😭 \n 이제 innoHI 사이트를 스마트폰으로도 접속하실 수 있도록 준비중입니다. \n 새로운 모습과 알찬 내용으로 AWS에서 다시 태어날 innoHI 사이트를 기대해주세요🥰",
    "img" : "4.innoHI_renewal.png",
    "button" : "N",
    "link" : ""
  }
];

export const techPickTestData = [
  {
    "bno": 7,
    "boardType": 2,
    "noticeYn": 0,
    "title": "[Biz Pick] 여행 전망",
    "content": ["1.png", "2.png", "3.png", "4.png"],
    "regUser": "관리자",
    "regDate": "2022-02-24 08:49:39",
    "updtUser": null,
    "updtDate": null,
    "viewCnt": 0
  },
  {
    "bno": 6,
    "boardType": 1,
    "noticeYn": 0,
    "title": "혁신이지33차 (D2C의 시대)",
    "content": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg"],
    "regUser": "관리자",
    "regDate": "2022-02-07 04:49:39",
    "updtUser": null,
    "updtDate": null,
    "viewCnt": 0
  },
  {
    "bno": 5,
    "boardType": 1,
    "noticeYn": 0,
    "title": "혁신이지26차 (이케아)",
    "content": ["0.png", "1.png", "2.png", "3.png", "4.png", "5.png", "6.png", "7.png", "8.png"],
    "regUser": "관리자",
    "regDate": "2022-02-07 04:49:39",
    "updtUser": null,
    "updtDate": null,
    "viewCnt": 0
  },
  {
    "bno": 4,
    "boardType": 1,
    "noticeYn": 0,
    "title": "혁신이지20차 (라이다)",
    "content": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg", "10.jpg" , "11.jpg"],
    "regUser": "관리자",
    "regDate": "2022-02-07 04:49:39",
    "updtUser": null,
    "updtDate": null,
    "viewCnt": 0
  },
  {
    "bno": 3,
    "boardType": 1,
    "noticeYn": 0,
    "title": "혁신이지17차 (금손들의 아마존)",
    "content": ["01.jpg", "02.jpg", "03.jpg", "04.jpg", "05.jpg", "06.jpg", "07.jpg", "08.jpg", "09.jpg", "10.jpg"],
    "regUser": "관리자",
    "regDate": "2022-02-07 04:49:39",
    "updtUser": null,
    "updtDate": null,
    "viewCnt": 0
  },
  {
    "bno": 2,
    "boardType": 1,
    "noticeYn": 0,
    "title": "혁신이지14차 (고스트 키친)",
    "content": ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg", "7.jpg", "8.jpg", "9.jpg"],
    "regUser": "관리자",
    "regDate": "2022-02-07 04:49:39",
    "updtUser": null,
    "updtDate": null,
    "viewCnt": 0
  },
  {
    "bno": 1,
    "boardType": 1,
    "noticeYn": 0,
    "title": "혁신이지3차 (디지털 캠프파이어)",
    "content": ["디지털-캠프파이어-1.jpg", "디지털-캠프파이어-2.jpg", "디지털-캠프파이어-3.jpg", "디지털-캠프파이어-4.jpg", "디지털-캠프파이어-5.jpg", "디지털-캠프파이어-6.jpg"],
    "regUser": "관리자",
    "regDate": "2022-02-07 04:49:39",
    "updtUser": null,
    "updtDate": null,
    "viewCnt": 0
  }
];

export const newsletterTestData = [
  {
    "bno": 9,
    "boardType": 1,
    "noticeYn": 0,
    "title": "[이노하이레터#14] 01월3주차 뉴스레터 📭",
    "content": "https://oinewsletter.s3.ap-northeast-2.amazonaws.com/image/20211210/(211210)+OI+%EB%89%B4%EC%8A%A4%EB%A0%88%ED%84%B0+%EC%B5%9C%EC%A2%85%EB%B3%B8.html",
    "regUser": "작성자6",
    "regDate": "2022-01-13 02:09:39",
    "updtUser": "inhyeok",
    "updtDate": "2021-11-06",
    "viewCnt": 1
  },
  {
    "bno": 8,
    "boardType": 1,
    "noticeYn": 0,
    "title": "[이노하이레터#13] 01월2주차 뉴스레터 📭",
    "content": "https://oinewsletter.s3.ap-northeast-2.amazonaws.com/image/20211210/(211210)+OI+%EB%89%B4%EC%8A%A4%EB%A0%88%ED%84%B0+%EC%B5%9C%EC%A2%85%EB%B3%B8.html",
    "regUser": "작성자6",
    "regDate": "2022-01-13 02:09:39",
    "updtUser": "inhyeok",
    "updtDate": "2021-11-06",
    "viewCnt": 1
  },
  {
    "bno": 7,
    "boardType": 1,
    "noticeYn": 0,
    "title": "[이노하이레터#12] 01월1주차 뉴스레터 📭",
    "content": "https://oinewsletter.s3.ap-northeast-2.amazonaws.com/image/20211210/(211210)+OI+%EB%89%B4%EC%8A%A4%EB%A0%88%ED%84%B0+%EC%B5%9C%EC%A2%85%EB%B3%B8.html",
    "regUser": "작성자6",
    "regDate": "2022-01-13 02:09:39",
    "updtUser": "inhyeok",
    "updtDate": "2021-11-06",
    "viewCnt": 1
  },
  {
    "bno": 6,
    "boardType": 1,
    "noticeYn": 0,
    "title": "[이노하이레터#11] 12월4주차 뉴스레터 📭",
    "content": "https://oinewsletter.s3.ap-northeast-2.amazonaws.com/image/20211210/(211210)+OI+%EB%89%B4%EC%8A%A4%EB%A0%88%ED%84%B0+%EC%B5%9C%EC%A2%85%EB%B3%B8.html",
    "regUser": "작성자6",
    "regDate": "2022-01-13 02:09:39",
    "updtUser": "inhyeok",
    "updtDate": "2021-11-06",
    "viewCnt": 1
  },
  {
    "bno": 5,
    "boardType": 1,
    "noticeYn": 0,
    "title": "[이노하이레터#10] 12월2주차 뉴스레터 📭",
    "content": "https://oinewsletter.s3.ap-northeast-2.amazonaws.com/image/20211210/(211210)+OI+%EB%89%B4%EC%8A%A4%EB%A0%88%ED%84%B0+%EC%B5%9C%EC%A2%85%EB%B3%B8.html",
    "regUser": "\t작성자5",
    "regDate": "2021-10-20 04:50:01",
    "updtUser": null,
    "updtDate": null,
    "viewCnt": 0
  },
  {
    "bno": 4,
    "boardType": 1,
    "noticeYn": 0,
    "title": "테스트 제목4",
    "content": "https://oinewsletter.s3.ap-northeast-2.amazonaws.com/image/20211210/(211210)+OI+%EB%89%B4%EC%8A%A4%EB%A0%88%ED%84%B0+%EC%B5%9C%EC%A2%85%EB%B3%B8.html",
    "regUser": "\t작성자4",
    "regDate": "2021-10-20 04:50:01",
    "updtUser": null,
    "updtDate": null,
    "viewCnt": 0
  },
  {
    "bno": 3,
    "boardType": 1,
    "noticeYn": 0,
    "title": "테스트 제목3",
    "content": "https://oinewsletter.s3.ap-northeast-2.amazonaws.com/image/20211210/(211210)+OI+%EB%89%B4%EC%8A%A4%EB%A0%88%ED%84%B0+%EC%B5%9C%EC%A2%85%EB%B3%B8.html",
    "regUser": "\t작성자3",
    "regDate": "2021-10-20 04:50:01",
    "updtUser": null,
    "updtDate": null,
    "viewCnt": 0
  },
  {
    "bno": 2,
    "boardType": 1,
    "noticeYn": 0,
    "title": "테스트 제목2",
    "content": "https://oinewsletter.s3.ap-northeast-2.amazonaws.com/image/20211210/(211210)+OI+%EB%89%B4%EC%8A%A4%EB%A0%88%ED%84%B0+%EC%B5%9C%EC%A2%85%EB%B3%B8.html",
    "regUser": "\t작성자2",
    "regDate": "2021-10-20 04:50:01",
    "updtUser": null,
    "updtDate": null,
    "viewCnt": 0
  },
  {
    "bno": 1,
    "boardType": 1,
    "noticeYn": 0,
    "title": "테스트 제목1",
    "content": "https://oinewsletter.s3.ap-northeast-2.amazonaws.com/image/20211210/(211210)+OI+%EB%89%B4%EC%8A%A4%EB%A0%88%ED%84%B0+%EC%B5%9C%EC%A2%85%EB%B3%B8.html",
    "regUser": "\t작성자1",
    "regDate": "2021-10-20 04:49:39",
    "updtUser": null,
    "updtDate": null,
    "viewCnt": 0
  }
];


export const startupTestData = [
        {
          "S_NO": 1,
          "S_NAME": "Neteera",
          "S_CATEGORY": "의료",
          "S_TECH_TYPE": "IoT",
          "S_MAIN_SERVICE": "비접촉 Vital Signs 모니터링 솔루션",
          "S_EMPLOYEE_NUM": "30인(정규직 30명, 계약직 0명)",
          "S_LOCATION": "이스라엘 예루살렘",
          "S_SERVICE_DETL": "1)마이크로 레이더 칩과 알고리즘을 활용해 심박수, 심박변이도, 호홉수, 호홉의 진폭과 같은 생체 신호를 체크하는 센서 기술\n    2) 센서칩을 가구나 의류에 부착해 지속적으로 모니터링이 가능\n    3) Neteera 130W 하드웨어(6*8cm규격) B2B 서비스가 주요 사업 모델",
          "S_SPECIAL_FEATURE": "- 마이크로 레이더(sub-Terahertz frequencies)를 활용한 마이크로 센서\n    - 의자, 침대, 키오스크에 임베디드해서 병원 뿐 아니라 차량, 홈 모니터링, 공항, 공공 시설 등 다양한 분야에 적용 가능",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 2,
          "S_NAME": "Smedo",
          "S_CATEGORY": "의료",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "비접촉 생체 신호 모니터링 서비스",
          "S_EMPLOYEE_NUM": "5인(정규직 5명, 계약직 0명)",
          "S_LOCATION": "독일 베를린",
          "S_SERVICE_DETL": "1) 심박수, 심박변이도, 심장소리, 호홉수, 호홉의 진폭을 측정, 혈압측정은 개발중\n    2) ECG(접촉 없이 24시간 동안 모니터링 담당)\n    3) 7m 반경 내 측정 가능(어둠 속, 의류나 가구가 있어도)",
          "S_SPECIAL_FEATURE": "- 유아돌연사 방지 모니터링 \n    - 중증노인 24시간 모니터링\n    - 코로나 증상자 관리\n    - 의자에 앉아 있는 사람의 생체 신호 추적",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 3,
          "S_NAME": "HealthBeats",
          "S_CATEGORY": "의료",
          "S_TECH_TYPE": "IoT",
          "S_MAIN_SERVICE": "원격 환자 모니터링 플랫폼",
          "S_EMPLOYEE_NUM": "10인(정규직 8명, 계약직 2명)",
          "S_LOCATION": "싱가포르",
          "S_SERVICE_DETL": "1) iHealth Labs(실리콘밸리 업체)의 IoT의료 기구 유통업체\n    2) IoT 의료기구와 연동된 앱에 저장되는 신체 정보를 관리해 주는 서비스",
          "S_SPECIAL_FEATURE": " - 3일내 빠른 배포와 사용자 편리성 강조\n    - 의료종사자를 위한 페이퍼리스 지원\n    - 환자당 월정액 모델",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 4,
          "S_NAME": "Binah.ai",
          "S_CATEGORY": "의료",
          "S_TECH_TYPE": "AI",
          "S_MAIN_SERVICE": "비디오기반 바이탈사인 모니터링",
          "S_EMPLOYEE_NUM": "28인(정규직 28명, 계약직 0명)",
          "S_LOCATION": "이스라엘 텔아비브",
          "S_SERVICE_DETL": "1) 1분동안 카메라를 쳐다보면 vital signs을 확인(AI, ML기술)\n    2) 심박수, 산소포화도, 호홉수, 스트레스 측정(서양인 기준), 혈압(제공 예정)\n    3) SDK 제공(iOS, Android, Windows)\n    4) 95~98% 의료수준의 정확도 보장",
          "S_SPECIAL_FEATURE": " - 빛을 활용해, 혈액이 심장에서 물결 모양을 이루며 전파되는 모습을 진단하는 원격 광용적맥파(rPPG : remote Photoplethysmographic imaging) 기술 이용\n    - 손가락을 스마트폰 후면 카메라에 대는 PPG 측정도 가능",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 5,
          "S_NAME": "Nuralogix",
          "S_CATEGORY": "의료",
          "S_TECH_TYPE": "AI",
          "S_MAIN_SERVICE": "원격 환자 건강 모니터링 앱",
          "S_EMPLOYEE_NUM": "60인(정규직 60명, 계약직 0명)",
          "S_LOCATION": "캐나다 토론토",
          "S_SERVICE_DETL": "1) 앱서비스명 Anura(무료 이용 가능)\n    2) 30초동안 스마트폰(태블릿) 카메라를 쳐다보면 vital signs(심박수, 불규칙심장박동, 호홉수, 혈압, 심박변이도, 스트레스, 심혈관질환 위험)을 확인\n    3) DeepAffex(AI engine) dashboard",
          "S_SPECIAL_FEATURE": "- 경피 광학 이미징 기술(Transdermal Optical Imaginf) 이용\n    - 헬스케어, 직원복지, AR/VR 적용, 마켓 서베이 활용, 미디어/비디오 분석, 홈 어시스턴트 산업분야에 활용",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 6,
          "S_NAME": "ContunUse Biometrics",
          "S_CATEGORY": "의료",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "AI 기반 비접촉식 건강 모니터링 플랫폼",
          "S_EMPLOYEE_NUM": "50인(정규직 50명, 기술직종 75%)",
          "S_LOCATION": "이스라엘 텔아비브",
          "S_SERVICE_DETL": "1) 실시간 운전자 용 Cu-bx 센서 기반 일반 운전자 및 직업 운전자 모니터링 S/W 기술\n    2) 운전자 스트레스, 피로도 등 감지 시스템",
          "S_SPECIAL_FEATURE": "- 홈모니터링 툴, 만성질환 환자 모니터링 등 기존 전자 제품 및 의료 기구에 손쉽게 통합 가능",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 7,
          "S_NAME": "FundamentalVR",
          "S_CATEGORY": "의료",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "VR 가상 훈련 플랫폼",
          "S_EMPLOYEE_NUM": "50인(정규직 50명, 계약직 0명)",
          "S_LOCATION": "영국 런던",
          "S_SERVICE_DETL": "1) HapticVR(실제 촉감 VR) 플랫폼으로 병원 외과의 또는 관련 종사자 대상 실습 훈련 플랫폼",
          "S_SPECIAL_FEATURE": "- 가상 현실 (VR)과 촉각 결합 교육\n    - 미국 정형 외과 의사 아카데미 인증한 교육 시뮬레이션\n    - Oculus Quest 및 HTC Vive Focus Plus 등 독립형 VR 헤드셋에 제공\n    - 대규모 수술 시뮬레이션",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 8,
          "S_NAME": "Proprio Vision",
          "S_CATEGORY": "의료",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "머신러닝, AR 기반 수술 정확도 향상 서비스",
          "S_EMPLOYEE_NUM": "50인(정규직 50명, 계약직 0명)",
          "S_LOCATION": "미국 시애틀",
          "S_SERVICE_DETL": "1) 기계학습, 자동화된 인텔리전스, 혼합현실을 활용한 차세대 수술 탐색 및 영상 플랫폼",
          "S_SPECIAL_FEATURE": "1) 수술용 현미경, 항법 시스템, 루프, 스크린을 대체하는 솔루션\n    2) 수술 정확도 개선, 수술 워크플로우 단순화를 통한 수술 결과 향상",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 9,
          "S_NAME": "OramaVR",
          "S_CATEGORY": "의료",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "헬스케어 VR  가상 훈련 플랫폼",
          "S_EMPLOYEE_NUM": "50인(정규직 50명, 계약직 0명)",
          "S_LOCATION": "스위스 제네바",
          "S_SERVICE_DETL": "1) 최첨단 VR 기술을 통한 수술 시뮬레이션 교육 및 유명 외과의와 동시에 의료 교육 및 평가  ",
          "S_SPECIAL_FEATURE": "1) 최대 7명의 사용자 동시 접속\n    2) 시공간의 제약없이 의료 훈련\n    3) 온라인 보고서 관리 및 평가로 고품질 교육 제공\n    4) 다양한 products 출시 ORAMA-TKA, ORAMA-THA, ORAMA-CO-OP, ORAMA-DENTAL, ORAMA-SKILLS 등",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 10,
          "S_NAME": "Surgical Theater",
          "S_CATEGORY": "의료",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "신경외과 수술전 리허설 플랫폼 ",
          "S_EMPLOYEE_NUM": "50인(정규직 50명, 계약직 0명)",
          "S_LOCATION": "미국 서니베일",
          "S_SERVICE_DETL": "1) 신경외과의 수술 전 시뮬레이션과 사전 계획을 위한 수술 리허설 및 교육 트레이닝 플랫폼",
          "S_SPECIAL_FEATURE": "1) MRI나 CT 이미지 기반 3D 모델을 구축하는 ‘PrecisionVR’ 개발\n    2) 환자, 수술 계획, 의료전문가 협업 교육환경 플랫폼\n    3) 수술 전 환자에게 3D 영상 인지\n    4) 360도 동적 수술 시각화 및 계획\n    5) 의료전문가를 위한 몰입형 교육",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 11,
          "S_NAME": "8chili",
          "S_CATEGORY": "의료",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "홀로그래픽 협업과 교육 훈련 서비스 ",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "미국 샌프란시스코",
          "S_SERVICE_DETL": "1) 컴퓨터 비전, 혼합현실, 인공지능 등 심층 기술을 이용해 수술중인 외과 의사의 시야를 3D 라이브 비디오 재연하여, 고품질 수술 교육 서비스",
          "S_SPECIAL_FEATURE": "1) 외과 수술에 대한 정확도가 높은 정보에 대한 풍부한 데이터 레이크 구축이 목표\n    ➜ 로봇 시스템이 외부 도움 없이 개방적인 개입 수술을 수행할 수 있도록 하는 훈련 데이터 세트로 활용",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 12,
          "S_NAME": "Dual Good Health",
          "S_CATEGORY": "의료",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "VR 기반 헬스케어 훈련 서비스",
          "S_EMPLOYEE_NUM": "2인(정규직 2명,계약직 0명)",
          "S_LOCATION": "영국 런던",
          "S_SERVICE_DETL": "1) 심폐소생술을 훈련시키기 위한 VR 교육 컨텐츠 (참여형 시나리오 교육)",
          "S_SPECIAL_FEATURE": "1) 심폐소생술에 필수적인 손의 움직임을 정확하게 추적하여 흉부 압박 속도와 강도를 추적\n    2) 비상 생명 유지 교육을 위한 비용과 시간을 절약 (기존 제품의 절반 가격으로, 3분의1 정도의 시간 소요)",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 13,
          "S_NAME": "Osso VR",
          "S_CATEGORY": "의료",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "VR 수술 시뮬레이션 플랫폼",
          "S_EMPLOYEE_NUM": "13인(정규직 13명, 계약직 0명)",
          "S_LOCATION": "미국 팔로알토",
          "S_SERVICE_DETL": "1) 의료 서비스 제공자들(의사, 의료기기제조사 및 판매사 등)이 새로운 최첨단 의료기기를 실제적인 VR 시뮬레이션을 통해 최첨단 기술을 트레이닝 하도록 하는 수술 훈련 플랫폼",
          "S_SPECIAL_FEATURE": "1) 교과서와 실전 사이의 과정 간의 차이를 줄이기 위해 의료기기 제조업체와 협력",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 14,
          "S_NAME": "ImmersiveTouch",
          "S_CATEGORY": "의료",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "VR, AR, 햅틱 기술 기반 솔루션",
          "S_EMPLOYEE_NUM": "11~50인(정규직 11~50명, 계약직 0명)",
          "S_LOCATION": "미국 시카고",
          "S_SERVICE_DETL": "1) 3D VR 영상 기술과 햄틱 기술이 결합된 수술 시뮬레이션 및 교육 관리 플랫폼",
          "S_SPECIAL_FEATURE": "1) 환자 CT/MRI를 시뮬레이터에 로드하여 3D 수술 시뮬레이션 서비스\n    2) 가상 해부학 3D 이미지를 만지면서 느낄 수 있도록 하는 햅티 기술 적용으로 촉각 피드백 가능",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 15,
          "S_NAME": "Circulor",
          "S_CATEGORY": "APAC SUMMIT",
          "S_TECH_TYPE": "지속가능성",
          "S_MAIN_SERVICE": "공급망 추적 기술",
          "S_EMPLOYEE_NUM": "11~50명",
          "S_LOCATION": "영국",
          "S_SERVICE_DETL": "- 블록체인 기술을 활용한 공급망 추적 기술\n    - 공급망에 따라 탄소 배출량 측정 모니터링",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 16,
          "S_NAME": "Muuse",
          "S_CATEGORY": "APAC SUMMIT",
          "S_TECH_TYPE": "지속가능성",
          "S_MAIN_SERVICE": "재활용 컵 대여 서비스",
          "S_EMPLOYEE_NUM": "11~50명",
          "S_LOCATION": "싱가포르",
          "S_SERVICE_DETL": "- 모바일 앱을 통해 재활용 컵을 대여 및 반납\n    - 이용 시 음료 할인 등의 혜택을 제공",
          "S_SPECIAL_FEATURE": "- 앱서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 17,
          "S_NAME": "Sylvera",
          "S_CATEGORY": "APAC SUMMIT",
          "S_TECH_TYPE": "지속가능성",
          "S_MAIN_SERVICE": "탄소 발생 모니터링 서비스",
          "S_EMPLOYEE_NUM": "11~50명",
          "S_LOCATION": "영국",
          "S_SERVICE_DETL": "- 실시간 탄소 상쇄 모니터링\n    - 위성, 레이더 및 라이더 데이터 기반 머신 러닝",
          "S_SPECIAL_FEATURE": "- 웹서비스, API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 18,
          "S_NAME": "LISTEN FIELD",
          "S_CATEGORY": "APAC SUMMIT",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "농업용 수확 예측 플랫폼",
          "S_EMPLOYEE_NUM": "11~50명",
          "S_LOCATION": "일본",
          "S_SERVICE_DETL": "- 농업용 예측 API 서비스\n    - 현재 날씨, 계절 예측 및 기후 패턴 데이터 분석 기반 농산 작물 수확 시점과 예상 생산량을 예측",
          "S_SPECIAL_FEATURE": "- 웹/앱 서비스, API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 19,
          "S_NAME": "GreenHope",
          "S_CATEGORY": "APAC SUMMIT",
          "S_TECH_TYPE": "지속가능성",
          "S_MAIN_SERVICE": "바이오 플라스틱 소재 개발",
          "S_EMPLOYEE_NUM": "11~50명",
          "S_LOCATION": "인도네시아 자카르타",
          "S_SERVICE_DETL": "- 바이오 플라스틱 Ecoplas, Oxium 개발\n    - 제조사에 공급",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 20,
          "S_NAME": "Cropin ",
          "S_CATEGORY": "APAC SUMMIT",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "농업 생태계 관리 솔루션",
          "S_EMPLOYEE_NUM": "51-200명",
          "S_LOCATION": "인도",
          "S_SERVICE_DETL": "- 데이터 기반의 AI 분석을 통한 농업 생태계 관리 솔루션\n    - 제품 : SmartFarm, SmartRistk, SmartWare, RootTrace",
          "S_SPECIAL_FEATURE": "- 웹/앱 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 21,
          "S_NAME": "Jumper.AI",
          "S_CATEGORY": "APAC SUMMIT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "대화형 상거래 및 광고 플랫폼",
          "S_EMPLOYEE_NUM": "11~50명",
          "S_LOCATION": "싱가포르",
          "S_SERVICE_DETL": "- 대화형 e 커머스 솔루션",
          "S_SPECIAL_FEATURE": "- 웹/앱 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 22,
          "S_NAME": "AVANA ",
          "S_CATEGORY": "APAC SUMMIT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "온라인 비즈니스 올인원 솔루션",
          "S_EMPLOYEE_NUM": "11~50명",
          "S_LOCATION": "싱가포르",
          "S_SERVICE_DETL": "- 온라인 스토어, SNS 채팅 통합, 자동 회신, 리셀러 관리 기능",
          "S_SPECIAL_FEATURE": "- 웹/앱 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 23,
          "S_NAME": "Qiscus",
          "S_CATEGORY": "APAC SUMMIT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "Multi-Channel 채팅 플랫폼",
          "S_EMPLOYEE_NUM": "51-200명",
          "S_LOCATION": "싱가포르",
          "S_SERVICE_DETL": "- 채팅 및 통화, 화상 회의 기술 SDK 서비스\n    - 다채널의 대화를 통합 관리하는 채팅 플랫폼\n    - 제품/서비스 명 Multichannel Chat,WhatsApp API Only, In-App Chat SDK,CRM, Chatbot, Meet SDK",
          "S_SPECIAL_FEATURE": "- 웹/앱 서비스, SDK 제공",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 24,
          "S_NAME": "Freed",
          "S_CATEGORY": "APAC SUMMIT",
          "S_TECH_TYPE": "AI",
          "S_MAIN_SERVICE": "맞춤형 여행정보 제공 챗봇 솔루션",
          "S_EMPLOYEE_NUM": "11-50명",
          "S_LOCATION": "인도네시아",
          "S_SERVICE_DETL": "- AI 기반 챗봇 솔루션으로 여행자에게 맞춤형 실시간 여행정보 제공\n    - 제품/서비스명 ARA, TravelFlan, ShoppingFlan",
          "S_SPECIAL_FEATURE": "- 웹/앱 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 25,
          "S_NAME": "Imajin",
          "S_CATEGORY": "APAC SUMMIT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "제조를 위한 허브 플랫폼",
          "S_EMPLOYEE_NUM": "11-50명",
          "S_LOCATION": "인도네시아 자카르타",
          "S_SERVICE_DETL": "- 제품 제조의 전 과정, 디자인부터 제조, 배송 까지의 서비스 제공자를 연결해 주는 플랫폼",
          "S_SPECIAL_FEATURE": "- 웹서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 26,
          "S_NAME": "RekoSistem",
          "S_CATEGORY": "APAC SUMMIT",
          "S_TECH_TYPE": "지속가능성",
          "S_MAIN_SERVICE": "디지털 폐기물 수거 솔루션",
          "S_EMPLOYEE_NUM": "2-10명",
          "S_LOCATION": "인도네시아 자카르타",
          "S_SERVICE_DETL": "- 모바일 앱을 통해 재활용 분리 수거 신청, 수거 후 보상 제공\n    - IoT 스마트 드롭 박스 서비스(앱명: WhatsApp)\n    - 유기성 폐기물을 진환경 에너지 또는 생화학 물질로 전환하는 기술",
          "S_SPECIAL_FEATURE": "- 앱서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 27,
          "S_NAME": "Periksa",
          "S_CATEGORY": "APAC SUMMIT",
          "S_TECH_TYPE": "의료",
          "S_MAIN_SERVICE": "의료기록 분석 솔루션",
          "S_EMPLOYEE_NUM": "2-10명",
          "S_LOCATION": "인도네시아",
          "S_SERVICE_DETL": "- 클라우드 기반 SaaS 서비스\n    - 의료기룩 디지털화\n    - 의료데이터 AI 분석",
          "S_SPECIAL_FEATURE": "- 웹/앱 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 28,
          "S_NAME": "SPLIO",
          "S_CATEGORY": "SUMMER SUMMIT",
          "S_TECH_TYPE": "핀테크",
          "S_MAIN_SERVICE": "모바일 지갑",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "프랑스",
          "S_SERVICE_DETL": "- Native Application\n    - 항공기, 입장권, 바우처등의 관리\n    - 할인권, 프로모션 코드등을 제공\n    - 소비자 개개인에 특화된 Loyalty Program 제공",
          "S_SPECIAL_FEATURE": "- 앱 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 29,
          "S_NAME": "SPLYT",
          "S_CATEGORY": "SUMMER SUMMIT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "예약 플랫폼",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "영국",
          "S_SERVICE_DETL": "- 여행산업과 모빌리티에 대한 예약 플랫폼",
          "S_SPECIAL_FEATURE": "- 앱 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 30,
          "S_NAME": "HOTEL RUNNER",
          "S_CATEGORY": "SUMMER SUMMIT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "세일즈 관리 플랫폼",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "- SaaS\n    - 여행사, 숙박업체 및 결제 대행사 통합\n    - 세일즈 관리 플랫폼",
          "S_SPECIAL_FEATURE": "- 웹/앱 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 31,
          "S_NAME": "KYTE",
          "S_CATEGORY": "SUMMER SUMMIT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "예약 플랫폼",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "영국",
          "S_SERVICE_DETL": "- 항공기 예약 및 구매 프로세스 단순화, 명료화\n    - 예약시 Personalize된 경험 제공",
          "S_SPECIAL_FEATURE": "- API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 32,
          "S_NAME": "LAVARTI",
          "S_CATEGORY": "SUMMER SUMMIT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "공항 서비스 솔루션",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "영국",
          "S_SERVICE_DETL": "- 공항 Service의 Digital화 솔루션\n    - MAX Vision이라는 웹기반 Disruption Management 서비스를 제공",
          "S_SPECIAL_FEATURE": "- 웹/앱 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 33,
          "S_NAME": "GRAPEVINE",
          "S_CATEGORY": "SUMMER SUMMIT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "예약 플랫폼",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "영국",
          "S_SERVICE_DETL": " - A.I 기반\n    - 여행객에게 최적화된 예약 제공(호텔, transportation, activities...etc)",
          "S_SPECIAL_FEATURE": "- 앱 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 34,
          "S_NAME": "PAYPARC",
          "S_CATEGORY": "SUMMER SUMMIT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "예약 플랫폼",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "스페인",
          "S_SERVICE_DETL": "- API Based\n    - B2B platform으로 숙박업체와 여행업체들의 직접적인 Connection을 구성\n    - 예약 프로세스의 효율성 증대",
          "S_SPECIAL_FEATURE": "- API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 35,
          "S_NAME": "LIVN",
          "S_CATEGORY": "SUMMER SUMMIT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "예약 플랫폼",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "호주",
          "S_SERVICE_DETL": "- 여행 상품 예약 프로세스 단순화 API\n    - 기존 예약시 각각의 업체별로 따로 예약이 진행되었던 비효율적 예약구조를 하나의 플랫폼화",
          "S_SPECIAL_FEATURE": "- API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 36,
          "S_NAME": "DUFFEL",
          "S_CATEGORY": "SUMMER SUMMIT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "예약 플랫폼",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "영국",
          "S_SERVICE_DETL": "- API Base\n    - 여행상품, 액티비티, 어트랙션 예약시스템",
          "S_SPECIAL_FEATURE": "- API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 37,
          "S_NAME": "CHOOSE",
          "S_CATEGORY": "SUMMER SUMMIT",
          "S_TECH_TYPE": "지속가능성",
          "S_MAIN_SERVICE": "탄소 추적 API 서비스",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "노르웨이",
          "S_SERVICE_DETL": "- 여행산업에서 발생하는 탄소발자국 추적",
          "S_SPECIAL_FEATURE": "- API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 38,
          "S_NAME": "PATCH",
          "S_CATEGORY": "SUMMER SUMMIT",
          "S_TECH_TYPE": "지속가능성",
          "S_MAIN_SERVICE": "탄소 방출량 계산 API 서비스",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "- 여행산업에서 발생하는 탄소 방출량과 발자국을 계산\n    - Carbon Removal 을 위한 플랫폼 제공",
          "S_SPECIAL_FEATURE": "- API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 39,
          "S_NAME": "Thrust Carbon",
          "S_CATEGORY": "SUMMER SUMMIT",
          "S_TECH_TYPE": "지속가능성",
          "S_MAIN_SERVICE": "탄소 배출량 계산 API",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "영국",
          "S_SERVICE_DETL": "- 데이터 분석\n    - 여행 산업을 통해 만들어 지는 여러 데이터 분석해 탄소 배출량을 계산",
          "S_SPECIAL_FEATURE": "- API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 40,
          "S_NAME": "LaaSie",
          "S_CATEGORY": "SUMMER SUMMIT",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "Loyalty Program",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "- Loyalty program 서비\n    - AI기반\n    - 소비자 개개인에 최적화된 Rewards와 Gratification을 제공 ",
          "S_SPECIAL_FEATURE": "- 웹/앱 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 41,
          "S_NAME": "ZYTLYN",
          "S_CATEGORY": "SUMMER SUMMIT",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "데이터 분석 플랫폼",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "스위스",
          "S_SERVICE_DETL": "- 데이터 분석\n    - 분석된 데이터 모델을 통해 의사 결정 과정의 최적화에 도움",
          "S_SPECIAL_FEATURE": "- API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 42,
          "S_NAME": "BEYOND PRICING",
          "S_CATEGORY": "SUMMER SUMMIT",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "세일즈 관리 플랫폼",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "- 매출 관리\n    - 동적 가격 책정 시스템\n    - 단기 숙박 렌탈 관리 시스템",
          "S_SPECIAL_FEATURE": "- API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 43,
          "S_NAME": "NETHONE",
          "S_CATEGORY": "SUMMER SUMMIT",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "고객 정보 분석 시스템",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "폴란드",
          "S_SERVICE_DETL": "- 데이터 분석을 여행 상품 예약시 Bot 및 Fraud 탐지 솔루션",
          "S_SPECIAL_FEATURE": "- API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 44,
          "S_NAME": "SEADRONIX",
          "S_CATEGORY": "NEXT RISE",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "접안 모니터링 시스템",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "대한민국 울산광역시",
          "S_SERVICE_DETL": "- 인공지능 기술 기반\n    - SxAS100A-CM이라는 센서 모듈을 사용\n    - 실시간 영상 촬영을 통한 위치 및 자세 측정, 실시간 데이터 획득 및 모니터링\n    - 조명탑, 크레인등의 기존 시설물에 설치 가능",
          "S_SPECIAL_FEATURE": "- 웹/앱 서비스, 자사 센서 모듈",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 45,
          "S_NAME": "SEOUL ROBOTICS",
          "S_CATEGORY": "NEXT RISE",
          "S_TECH_TYPE": "AI",
          "S_MAIN_SERVICE": "3D 컴퓨터 비전 시스템",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "대한민국 서울특별시",
          "S_SERVICE_DETL": "- AI기반\n    - 실내, 야외 모든 공간에서 객체 감지, 추적 및 분류가 가능\n    - 자율주행, AV/ADAS, 스마트 시티와 인프라, 교통 안전등 여러 시장에 적용 가능\n    - 객체 추적의 정확도에 따라 물류센터에서 롤테이너 추적등에 활용 가능 예상",
          "S_SPECIAL_FEATURE": "- API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 46,
          "S_NAME": "지와이 네트웍스",
          "S_CATEGORY": "NEXT RISE",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "현장관리 시스템",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "대한민국 인천광역시",
          "S_SERVICE_DETL": "- AI 기반\n    - 기존 설치되어 있는 CCTV를 통해 화재, 선반붕괴와 같은 위험상황 감지\n    - 이상 발생시 관리자/처리팀에 즉각적인 연락\n    - 배회자(거동수상자), 안전장구 미착용등 현장관리영역에서도 사용가능\n    - 물류터미널, 서버실과 같은 시설에서 활용 가능",
          "S_SPECIAL_FEATURE": "- API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 47,
          "S_NAME": "VOUCH",
          "S_CATEGORY": "NEXT RISE",
          "S_TECH_TYPE": "AI",
          "S_MAIN_SERVICE": "AI 챗봇 기반의 디지털 컨시어지 솔루션",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "싱가포르",
          "S_SERVICE_DETL": "- AI 챗봇 기반의 디지털 솔루션\n    - 현재 전세계 30여개의 호텔을 대상으로 서비스중\n    - 숙박 및 부대시설 예약\n    - 체크인\n    - 컨시어지 서비스\n    - 물품 혹은 청소 요청 및 인 룸 다이닝 요청",
          "S_SPECIAL_FEATURE": "- 웹서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 48,
          "S_NAME": "뷰런 테크놀로지",
          "S_CATEGORY": "NEXT RISE",
          "S_TECH_TYPE": "자율주행",
          "S_MAIN_SERVICE": "LiDAR 인지 솔루션",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "대한민국 서울특별시",
          "S_SERVICE_DETL": "- 자율주행 및 산업용\n    - 끼어들기/동일차선 주행 차량 감지, 사각 감지, 차선 감지, 가드레일 감지, 지면 탐지(언덕 및 고가도로등), 터널 감지",
          "S_SPECIAL_FEATURE": "- API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 49,
          "S_NAME": "LOPLAT",
          "S_CATEGORY": "NEXT RISE",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "Wi-Fi Fingerprint기술을 활용한 사용자 위치 확인 솔루션",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "대한민국 서울특별시",
          "S_SERVICE_DETL": "- SaaS\n    - Wi-Fi, GPS, Bluetooth, 비콘등 여러 신호로 동작가능\n    - 신호를 발산할 Tracker와 신호를 받아 처리할 Receiver를 따로 설치필요\n    - 현재 구성 가능한 Beacon 기반의 추적 시스템과 비교시 명확한 장점은 없음",
          "S_SPECIAL_FEATURE": "- API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 50,
          "S_NAME": "디토닉",
          "S_CATEGORY": "NEXT RISE",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "시공간 데이터 분석 솔루션",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "경기도 안양시",
          "S_SERVICE_DETL": "- 실시간 시공간 데이터 분석 솔루션\n    - 시공간 데이터를 빅데이터를 통해 분석\n    - 현재 현대차그룹과 한국교통공단에서 교통량분석 및 네비게이션 사업에 활용중\n    - 물류 이동 경로 파악 및 재고 관리등의 영역에서 활용이 가능 예상",
          "S_SPECIAL_FEATURE": "- API 서비스",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 51,
          "S_NAME": "WILLOG",
          "S_CATEGORY": "NEXT RISE",
          "S_TECH_TYPE": "IoT",
          "S_MAIN_SERVICE": "OTQ 태그를 통한 물류 이력관리",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "대한민국 서울특별시",
          "S_SERVICE_DETL": "- 물류 이력관리 솔루션\n    - 생산지부터 소바자 단계까지 모든 물류 유통 과정을 기록하고 관리가능\n    - OTQ 태그에 온도, 습도, 충격 내역등이 저장\n    - 네트워크 연결이 불가능한 곳에서도 로그가 작성되는 장점이 있음\n    - 로그 조작과 데이터 변형으로부터 안전",
          "S_SPECIAL_FEATURE": "- 자사 솔루션",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 52,
          "S_NAME": "플랫폼베이스",
          "S_CATEGORY": "NEXT RISE",
          "S_TECH_TYPE": "IoT",
          "S_MAIN_SERVICE": "스마트락",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "경기도 수원시",
          "S_SERVICE_DETL": "- 플랫폼기반의 ICT 소형 잠금장치\n    - 디지털락과 스마트키로 구성\n    - 키별로 권한등급을 따로 설정가능\n    - 관제 소프트웨어를 통해 사용기록 확인 및 일회용 권한 부여 가능\n    - 실시간 자물쇠 위치 정보 지도위에 표출 가능\n    - 대부분의 보안장치에서 사용 가능",
          "S_SPECIAL_FEATURE": "- 웹/앱 서비스, 제품",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 53,
          "S_NAME": "ARVIZON",
          "S_CATEGORY": "NEXT RISE",
          "S_TECH_TYPE": "모빌리티",
          "S_MAIN_SERVICE": "차량용 블랙박스",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "대한민국 인천광역시",
          "S_SERVICE_DETL": "- 360도 촬영이 가능한 차량용 블랙박스\n    - 모델명 VEZO 360\n    - 졸음방지, 충돌방지기능 또한 지원\n    - 일반적인 블랙박스와 동일한 장착위치\n    - 화물트레일러 등에서는 2개이상의 카메라 설치가 필요해 보임.",
          "S_SPECIAL_FEATURE": "- 제품",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 54,
          "S_NAME": "ITED",
          "S_CATEGORY": "NEXT RISE",
          "S_TECH_TYPE": "모빌리티",
          "S_MAIN_SERVICE": "투명 열선기술",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "경기도 하남시",
          "S_SERVICE_DETL": "- 저전력 투명열선 기술\n    - 차량 유리에 생기는 성에와 김서림 등을 제거\n    - 성에, 김서림으로 인한 안전사고를 방지\n    - 소형화가 가능하다면 카메라 렌즈, CCTV 등에 도입하여 사용 가능",
          "S_SPECIAL_FEATURE": "- 제품",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 55,
          "S_NAME": "마이크로 시스템즈",
          "S_CATEGORY": "NEXT RISE",
          "S_TECH_TYPE": "모빌리티",
          "S_MAIN_SERVICE": "Anti Drop Glass",
          "S_EMPLOYEE_NUM": "정보 없음",
          "S_LOCATION": "경기도 용인시",
          "S_SERVICE_DETL": "- 우천시 렌즈에 맺히는 물방울들을 제거\n    - 자율주행 차량의 렌즈, 드론, CCTV등에 활용 가능\n    - 현재 현대차 그룹에 납품 중\n    - 차량 전면 유리 반개정도의 크기까지 개발됨",
          "S_SPECIAL_FEATURE": "- 제품",
          "S_RESEARCHED_TIME": "2021"
        },
        {
          "S_NO": 56,
          "S_NAME": "OneAire",
          "S_CATEGORY": "Batch9 Selection Day",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "항공 및 분석 디지털 솔루션",
          "S_EMPLOYEE_NUM": "7명",
          "S_LOCATION": "에스토니아",
          "S_SERVICE_DETL": "- 문서 디지털화\n    - 규정 감사 지원\n    - 프로세스 자동화",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 57,
          "S_NAME": "ZestIOT",
          "S_CATEGORY": "Batch9 Selection Day",
          "S_TECH_TYPE": "IoT",
          "S_MAIN_SERVICE": "IoT/AI 기반 항공 플랫폼",
          "S_EMPLOYEE_NUM": "11 ~ 50명",
          "S_LOCATION": "인도",
          "S_SERVICE_DETL": "- 지상운영 및 탑승수속 자동화\n    - 수하물 추적",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 58,
          "S_NAME": "Airportr",
          "S_CATEGORY": "Batch9 Selection Day",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "온라인 수하물 체크인 및 배송 서비스",
          "S_EMPLOYEE_NUM": "60명",
          "S_LOCATION": "영국",
          "S_SERVICE_DETL": "- 수하물 데스크를 온라인화",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 59,
          "S_NAME": "Segment",
          "S_CATEGORY": "Batch9 Selection Day",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "고객 데이터 분석 솔루션",
          "S_EMPLOYEE_NUM": "500명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "- 웹, 모바일 앱에서 사용자 이벤트를 수집하여, 회사에 맞는 완벽한 데이터 툴킷(마케팅 활용, 데이터 분석, API 활용 등)을 제공\n    - 200개 이상의 마케팅, 분석 및 데이터 웨어하우스 도구에 연결 가능\n    - 스타트업부터 대기업까지 고객사가 있으며, 각 기업의 규모와 산업(모바일, B2B, 미디어 등)에 맞는 솔루션 제공",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 60,
          "S_NAME": "Cloudleaf, Inc",
          "S_CATEGORY": "Batch9 Selection Day",
          "S_TECH_TYPE": "IoT",
          "S_MAIN_SERVICE": "디지털 공급망 솔루션",
          "S_EMPLOYEE_NUM": "40명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "- 모든 소스에서 데이터를 수집하여 공급망에서 자재 및 자산(제품)의 상황, 상태, 시기 및 위치에 대한 지속적인 가시성 제공\n    - 재고 관리 및 물류 최적화, 규제와 규칙 준수 비율 향상, 협업 개선 후 신속하고 빠른 전략적 결정 지원, 재무 성과 및 고객 만족도 향상\n    - 공급자에서 제조, 유통에 이르는 end-to-end 공급망 전체 가치 창출 지원",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 61,
          "S_NAME": "project-44",
          "S_CATEGORY": "Batch9 Selection Day",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "배송 업체 및 제3자 물류를 위한 세계 최고의 물류 가시성 플랫폼",
          "S_EMPLOYEE_NUM": "88명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "- 배송업체와 3PLs(제 3자물류, 아웃소싱)의 고객 환경 개선하여 운영 효율성을 높이고, 비용은 절감, 운송 성능 개선\n    - 유럽 최고 업체인 GateHouse Logistics 인수 후 글로벌 확장\n    - 선박 및 항구, 철도 및 복합 운송, 트럭 등 다양한 분야에 적용 가능",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 62,
          "S_NAME": "Paanini",
          "S_CATEGORY": "Batch9 Selection Day",
          "S_TECH_TYPE": "업무 자동화",
          "S_MAIN_SERVICE": "Big Data, AI 기반의 통합 플랫폼을 제공하는 자동화 솔루션",
          "S_EMPLOYEE_NUM": "100~200명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "- AI기반의 통합 자동화 솔루션을 제공\n    - Invoice Processing, Manu Transcription, Id Verification, Text or voice chat 외 기업의 단순 반복 업무 자동화\n    - 웹 기반으로 RPA 프로세스를 관리하며, 프로그래밍적 요소가 적은 것이 특징",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 63,
          "S_NAME": "3Victors",
          "S_CATEGORY": "항공",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "AI & 머신러닝을 이용한 대형 항공료 데이터 분석 시스템",
          "S_EMPLOYEE_NUM": "10명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 64,
          "S_NAME": "Veer Immersive Technologies INC.",
          "S_CATEGORY": "항공",
          "S_TECH_TYPE": "VR",
          "S_MAIN_SERVICE": "아시아 최초 공인 가상현실 승무원 항공 안전 훈련기",
          "S_EMPLOYEE_NUM": "6명",
          "S_LOCATION": "필리핀",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 65,
          "S_NAME": "Swae",
          "S_CATEGORY": "항공",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "아이디어 개발과 그룹 의사결정을 위한 AI 플랫폼",
          "S_EMPLOYEE_NUM": "4명",
          "S_LOCATION": "캐나다",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 66,
          "S_NAME": "Bolverk XR",
          "S_CATEGORY": "항공",
          "S_TECH_TYPE": "VR",
          "S_MAIN_SERVICE": "VR, AR, MR 기술을 사용한 교육 시스템",
          "S_EMPLOYEE_NUM": "10명",
          "S_LOCATION": "덴마크",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 67,
          "S_NAME": "Smooss",
          "S_CATEGORY": "항공",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "상품화 및 고객 관리 플랫폼",
          "S_EMPLOYEE_NUM": "12명",
          "S_LOCATION": "프랑스",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 68,
          "S_NAME": "Actiw Intralogistics",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "변형 및 개조되지 않은 트레일러 및 컨테이너에 대한 완전 자동화된 원샷 적재 솔루션",
          "S_EMPLOYEE_NUM": "25명",
          "S_LOCATION": "핀란드",
          "S_SERVICE_DETL": "공장 내 물류 자동화(AGV/ASRS)가 존재하는 제조 장소(그린필드/브라운필드 상관 없음)에 통합되어 설치되는것을 선호.\n    볼륨 증가\n    ROI 향상\n    단독으로 독립 설치도 가능함",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 69,
          "S_NAME": "Dexterity, Inc.",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "이행능력, pick-&-place , 팔레타이징에 대해 인간과 같은 손재주를 가지는 AI 로봇 솔루션",
          "S_EMPLOYEE_NUM": "105명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "Dexterity의 목표는 고객과 협력하여 로봇 Dexterity 솔루션이 고객의 창고, 물류 및 공급망 운영을 어떻게 개선할 수 있는지 이해하는 것.\n    먼저 고객의 구체적인 요구 사항을 파악한 후 특정 Dexterity 로봇 사용 사례로 니즈를 세분화하여 마지막으로 시범 개발 및 공동 개발하는 등의 프로세스를 통해 고객별 맞춤 솔루션을 개발함",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 70,
          "S_NAME": "Dorabot",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "물류 및 전자상거래를 위한 AI 기반의 로보틱 솔루션",
          "S_EMPLOYEE_NUM": "51 ~ 100명",
          "S_LOCATION": "중국",
          "S_SERVICE_DETL": "팔, 손, 리프트 축 및 4개의 바퀴를 갖춘 Mobile Manipulator는 프로그램 가능한 22개의  자유각도(동작각도)를 가지고 있으며 조사 및 교육에 사용하기 위해 선전 대학에 의해 구입됨\n\n    창고 또는 소매점 내:\n    1. 자율 이동 로봇 또는 팔레트 잭을 이용한 상자/팔레트 운송\n    2. 로봇 피킹 스테이션 또는 모바일 피킹 로봇으로 제품 선택 및 보충(옴니 채널 분배)\n    3. 전자상거래 패키지 정렬(로봇 정렬 시스템)\n    4. 로봇 및 용기 계획 알고리즘을 사용한 팰릿라이징 및 컨테이너 적재\n\n    혜택 KPI: 단순 노동량, 창고 처리 효율성    \n    솔루션 KPI: 시간당 처리되는 부품/팔레트, 평균 자율 운행 시간\n    ROI: 사용 사례에 따라 2년 미만",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 71,
          "S_NAME": "Navflex",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "스마트 로지스틱 자동화",
          "S_EMPLOYEE_NUM": "3명",
          "S_LOCATION": "독일",
          "S_SERVICE_DETL": "Altmühltaler Mineralbrunnen GmbH: MVP는 시설 전반에서 점진적으로 차량을 배치하는것을 목표로 하며 광범위한 현장 테스트의 일환으로 Euro Pallet을 사용하는 고객 트레일러를 적재를 위해 매일 가동중임",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 72,
          "S_NAME": "Pickle Robotics",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "저비용 협업형 패키지 처리 로봇",
          "S_EMPLOYEE_NUM": "5명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "Pickle Robotics는 창고에서 자동화의 두 번째 단계인 \"선택된\" 개체를 쌓고 정리하는 작업을 하고 있음.\n    자사 로봇인 Dill은 패키지를 분류, 적재, 팔레타이징, 디팔레타이징 가능하며 이러한 기능을 사용해 다른 로봇들이 물건을 넣은 패키지를 팔레타이징 하는것으로 물류 이동을 원할하게 함.\n    Pickle은 단순히 패키지를 분류, 적재하는것 뿐만 아니라 적재된 패키지를 정렬하는 기능또한 고려중임.",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 73,
          "S_NAME": "Slip Robotics",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "단거리 물류 비효율성 개선을 위한 서비스형 로봇(RaaS) 솔루션",
          "S_EMPLOYEE_NUM": "3명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "다양한 시나리오에서 트럭 적재 및 하역 작업 개선 가능\n\n    실적용 사례(미국 중서부 제조업자의 엔진 제조 공장 적용)\n    1) 공장 가동시 3교대 근무\n    2) 주기적으로 창고에서 트럭으로 원재료를 적재(약 20분 주기)\n    3) 완제품 재고를 창고에 스테이징\n    4) 기존 트럭 운전자와 지게차 운전자 사이에 사이클마다 약 4시간의 노동량 발생\n\n    해당 사례에 Slip Robotics의 트럭 로딩 및 언로딩 솔루션 도입을 통해 기존 4시간가량의 노동량이 발생하던 업무를 30~40분으로 감소시켰음.\n    재료의 적재 시간을 최대 50%까지 감소 및 도크 도어와 작업 공간 요구량 감소시켰음.\n\n    이러한 사례를 통해 Slip Robotics의 솔루션은 자주 반복되는 단거리 물류에서 운영비용과 자본비용 모두를 절감 가능성을 증명함.",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 74,
          "S_NAME": "Vaculex",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "인체공학적 진공 리프터를 통한 상하차 보조",
          "S_EMPLOYEE_NUM": "55명",
          "S_LOCATION": "스웨덴",
          "S_SERVICE_DETL": "표준 장비뿐만 아니라 고객의 특정 요구에 맞게 조정된 맞춤형 Lifting 솔루션 제공\n\n    Lifter, Picker(Unloader), Trolleys, Crane, Lifter 부착부 Tool 등을 제공중\n\n    High-frequency lifting with TAWI\n    사용 가능 무게 : 65 kg 미만\n    동작 속도(들어올려지는 속도) : 0-1 m/s\n    부착판 크기: 1720 - 1840 mm\n    사용 가능 물품 : 박스, 드럼, 수화물, 식재 등등\n\n    Multifunctional vacuum lift systems\n    사용 가능 무게: < 270 kg\n    동작 속도(들어올려지는 속도) : 0-1 m/s\n    손잡이: 기본 / 한손형 / 유연형/ 확장형\n    여러 적재 상황에 맞는 다양한 툴 사용가능\n    가동범위 : 360도 회전",
          "S_SPECIAL_FEATURE": "Vaculex사가 Piab Group에 합병되며 Piab Group 내에서 유사 솔루션을 운용하고 있었던 TAWI 사와 합쳐짐 Vaculex TP는 TAWI High frequency lifter, Vaculex VL는 TAWI Multifunctional lifter, Vaculex ParceLift는 TAWI Telescopic mounted unloader로 서비스 명칭이 변경됨",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 75,
          "S_NAME": "Ancara Systems",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "표준형부터 커스터마이즈까지 대응 가능한 자동 트럭 상하차 솔루션",
          "S_EMPLOYEE_NUM": "11~50명",
          "S_LOCATION": "네덜란드",
          "S_SERVICE_DETL": "각 산업군에 맞는 상하차 자동화 솔루션 제공(JIT, 고중량 적재, Cold Chain, 고가의 Fragile 상품 적재 등)\n    Skateloader System, Carpet System, Conveyor System, Skate System, Roller Tracks 등 표준화된 트럭 적재(하차) 자동화 솔루션뿐만 아니라 커스터마이징 서비스도 제공중",
          "S_SPECIAL_FEATURE": "ATLS라고도 하는 자동 트럭(하역) 적재 시스템 분야의 전문가를 표방함.\n    표준 시스템에서부터 맞춤형 솔루션에 이르기까지 해당 업종에 적합한 물류 요구 사항을 충족하도록 시스템을 구성할 수 있음\n    20년 이상 전 세계적으로 트레일러 적재 및 하역 프로세스를 간소화하는 일을 해왔음",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 76,
          "S_NAME": "Duro Felguera",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "Stacker Cranes, Support Systems, Dimensional Controls등 물류 서비스에 필요한 대부분의 솔루션을 제공중",
          "S_EMPLOYEE_NUM": "1001~5000명",
          "S_LOCATION": "스페인",
          "S_SERVICE_DETL": "DF Logistics Systems는 자재 취급 및 보관 시스템과 다양한 응용 분야 및 섹터를 위한 완벽하고 자동화된 로지스틱 솔루션을 함께 제공함.\n    30년 이상의 물류 시스템 개발 경험을 가진 첨단 기술에 대한 심오한 지식을 자랑하는 엔지니어 및 프로그래머 팀이 고객의 물류 서비스를 위한 최고의 솔루션을 제공.\n    Stacker Cranes, Support Systems, Dimensional Controls등 물류 서비스에 필요한 대부분의 솔루션을 제공중",
          "S_SPECIAL_FEATURE": "CARES T2P 1500\n    Double Mast 형식\n    최대 허용 중량 1,500 kg\n    Europallet / American 형 팔렛 사용가능\n    한계 사용 높이 35 m\n    이동속도 / 가속도 - 3.3 m/s / 0.5 m/s2\n    리프트 속도 / 가속도 - 1 m/s / 0.5 m/s2\n    Telescopic fork 속도 / 가속도 -1.3 m/s / 1 m/s2\n\n    CARES T1M 100\n    Single Mast 형식\n    최대 허용 중량 100 kg\n    600*400 mm 화물 적재용\n    한계 사용 높이 10 m\n    이동속도 / 가속도 - 5 m/s / 3 m/s2\n    리프트 속도 / 가속도 - 2 m/s / 3 m/s2\n    Telescopic fork 속도 / 가속도 -1.3 m/s / 1 m/s2\n\n    PAJARES TRS 1500\n    최대 중량 1,500 kg\n    적재 형식 Europallet / American / Semipallet\n    길이 최대 6M\n    최소 동작 높이 200 mm\n    화물 이동속도 최대 0.5 m/s\n\n    DEVA ERP-800\n    화물 크기 1,200 x 1,800 mm\n    최대 적재 무게 UDC 800 kg\n    높이 3,600 mm\n    Stack 높이(최소/최대) 350/2,850 mm\n    Lift 속도 0.5 m/s",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 77,
          "S_NAME": "Deeyook",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "무선 기반, 기반시설 없이 저전력의 정확한 실/내외 위치 탐지 솔루션을 제공",
          "S_EMPLOYEE_NUM": "9명",
          "S_LOCATION": "이스라엘",
          "S_SERVICE_DETL": "특허받은 무선 기반의 자체 학습, 유비쿼터스, 초정밀(오차 10cm이하), 패시브 및 저전력의 펌웨어 솔루션으로 완벽한 실내외 위치 탐지 및 결정을 가능하게 함.\n\n    모든 사람 : 직원, 고객 및 응급 구조 대원들\n    모든 차량 : 일반 차량(Uber등), 화물 선박 및 무인 운반 차량등\n    모든 자재: \n    일반 자재 (예: 장기 차량 보관, 사무실 자산 등),\n    운송 자재 (예: 패키지, 수하물, 배송 팔레트 등)\n    이동 기기 (예: 스쿠터, 드론 등)\n\n    등에  적용가능",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 78,
          "S_NAME": "Intrasys RFID Solutions",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "IoT",
          "S_MAIN_SERVICE": "중요 자산 배치의 식별, 추적, 관리 및 최적화를 할 수 있는 RFID 기술 솔루션",
          "S_EMPLOYEE_NUM": "비공개",
          "S_LOCATION": "싱가포르",
          "S_SERVICE_DETL": "Intrasys는 정유 및 가스 산업에 사용되는 가스 실린더에 대한 자동 자산 추적 기능을 제공하는 RFID 가스 실린더 관리 솔루션 및 ATEX 인증 RFID 태그를 제공 중. 이를 통해 과거에 비해 가스  실린더를 보다 정확하게 추적이 가능해짐\n\n    자산 위치 정확도: 자산 위치 및 상태의 실시간 상태\n    프로세스 개선: 책임 및 즉각적인 알림\n    시스템 통합: ERP, 프로그램 관리, WMS 또는 기타 시스템을 위한 확장 가능한 인터페이스\n    장치 독립성: 유연한 구성으로 혼합 환경 통합 가능",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 79,
          "S_NAME": "Moeco",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "배송 상태 추적 및 모니터링 솔루션",
          "S_EMPLOYEE_NUM": "16명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "Moeco의 솔루션은 물류 공급망에 대한 완벽한 가시성과 추적을 가능하게함\n    - 패키지의 위치\n    - 보관 상태\n    - 배송 상태\n    - 온도\n    - 패키지 개봉 내역 (언제 / 어디서)\n\n    Moeco의 CPG/FMCG 솔루션은 제품의 생명주기에 대한 통찰과 모니터링 기능을 제공함\n    - 위치\n    - 배송 및 보관 상태\n    - 제품에 대한 이벤트 현황(개봉, 검수, 빈/가득찬 상태 등)\n    - 재활용 사항\n\n    Moeco는 비침해적 방식을 사용하여 도시(스마트 시티)와 산업 인프라 모두를 모니터링할 수 있는 데이터를 수신함\n    - 환경 조건(온도, 소음, 공기 품질)\n    - 사람 이동\n    - 전기 소비량\n    - 진동\n\n    Moeco의 예측 유지 보수 솔루션은 산업 인프라 모니터링 솔루션에 기반한 분석 서비스로 다음과 같은 기능을 지원함\n    - 장비 고장 예측\n    - 개조 없이 모든 유형의 장비 업그레이드",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 80,
          "S_NAME": "NanoThings",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "원산지에서 매장까지의 추적 솔루션",
          "S_EMPLOYEE_NUM": "9명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "문제점 : 고객은 1년간 1억개 가량의 공급망 폐기물 발생함\n\n    해결책 : NanoThings의 솔루션을 고객사의 배송과정에 도입하는 것으로 품질관리가 가능해졌고 기존 고객사에서 확인할 수 없었던 배송과정에 대한 가시성을 얻을 수 있었음.\n    결과 : NanoThings는 빠르게 고객사의 공급망에서 부주의한 운반자의 행동, 잘못된 거부, 온도 오남용, 잘못된 제품 취급을 포함한 문제가 있었던 영역에 대해 식별할 수 있었음. 이러한 문제를 확인할 수 있는 새로운 가시성 덕분에 그들은 빠르게 변화를 도입할 수 있었고, 연간 수백만 달러를 절감하고 있음",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 81,
          "S_NAME": "Oriient",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "실내 위치 포착(Indoor Positioning) 솔루션",
          "S_EMPLOYEE_NUM": "20명",
          "S_LOCATION": "이스라엘",
          "S_SERVICE_DETL": "사용자가 평범한 스마트폰을 손에 쥐고 공간 내부를 걸어다니는 것으로 자사 솔루션 Mapper가 빌딩의 전자기 풍경을 기록하며 이렇게 기록된 해당 시설의 전자기 지도는 Oriient사의 클라우드에 업로드됨.\n    자사 실내 GPS시스템은 iOS/Android 모바일 앱(데모 앱과 예제 코드가 포함된 경량 SDK를 통해 또는 Orient의 화이트 라벨 앱을 통해)에 통합됨\n    자사 알고리즘은 사용자의 스마트폰 센서 데이터를 마그네틱 맵과 함께 처리하여 사용자의 정확한 위치를 결정하고 사용자는 Oriient사의 서비스를 즐길 수 있으며 건물 소유자는 즉시 시설의 사용 및 관리에 대한 가시성을 얻을 수 있음.\n    관심 지점 위치 및 알림을 포함한 콘텐츠는 직관적인 대시보드를 사용하여 수정이 가능하며 외부 시스템의 API를 사용하여 데이터 활용이 가능함",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 82,
          "S_NAME": "Roambee",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "IoT",
          "S_MAIN_SERVICE": "IoT 기반의 기업급 자산 위치 추적 및 관리 솔루션",
          "S_EMPLOYEE_NUM": "70명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "The Bee라고 하는 무선 휴대용 모니터링 장치를 구축하여 Unilever사가 자사 출하품의 위치와 이동 상황을 실시간으로 확인할 수 있도록 서비스 중\n    Rambee의 on-demand기반 배송 추적 솔루션은 일반 차량에서도 특정 물류이송 그룹차량군처럼 동작가능. 이를통해 HUL사는 단일 배송 추적 솔루션을 사용하여 단일 대시보드에서 자사 전체 유통 네트워크를 커버가 가능해짐\n    Unilever사는 The Bee를 사용하여 각 아웃바운드 발송을 추적하며, 발송 또는 운송 유형에 관계없이 전용 웹 포털을 통해 모든 발송물을 추적할 수 있게 되었음.",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 83,
          "S_NAME": "Savi Technology",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "실시간 기반의 운송 중인 상품의 위치, 상태 및 보안 관리 솔루션",
          "S_EMPLOYEE_NUM": "180명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "한 글로벌 50 CPG(Consumer Packaged Goods) 업체는 북미 지역에서 매월 평균 25,000대의 트럭을 운송했지만 운송 중인 재고를 실시간으로 모니터링하는 시스템이 없었고, 운영 팀 구성원들은 이로인해 업무중 발생한 배송중단 상황을 인지하지 못했기 때문에 고객으로의 배송이 늦어지거나 배송이 되지 못하는 상황을 방지할 수 없었음\n    새로운 전략적인 교차 도킹 네트워크는 입고 도착 예상 시간의 부정확함과 교차 도킹할 수 있는 상품 수의 감소로 인해 높은 효율성에 대한 목표를 달성할 수 없음\n    TMS(Transport Management System) 과 ERP(Enterprise Resource Planning) 시스템은 실시간 정보를 수신하지 못했으며 배송 계획에 대한 업데이트를 거의 수신하지 못했음.\n    Savi는 고객과 협력하여 실시간 스트리밍 추적 및 ETA 솔루션인 Savi Visibility™를 구현하였음. CPG는 트럭 운송업체에 EDI(Electronic Data Interchange)와 telematics feeds를 Savi에 보내도록 요청했고, Savi는 계획된 운송을 기록하기 위해 CPG의 TMS와 주고받는 자동 피드를 설정하였음",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 84,
          "S_NAME": "Sigfox",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "네트워크",
          "S_MAIN_SERVICE": "낮은 처리량을 요구하는 연결된 객체들을 위한 전용 셀룰러 네트워크를 운영함",
          "S_EMPLOYEE_NUM": "500명",
          "S_LOCATION": "프랑스",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 85,
          "S_NAME": "ThingTech",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "기업 자산 관리 플랫폼 서비스",
          "S_EMPLOYEE_NUM": "19명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "경보시스템과 CCTV 감시, 경비원으로 조합된 기존의 도난방지 시스템은 효율성과 유연성이 떨어지고 이동수단에 대한 실시간 GPS 위치 추적이 불가능하기 때문에 ThingTech 고객들은 도난 방지를 위해 IoT 솔루션을 도입 중\n    고객사의 건설 장비에 ThingTech 위성위치확인시스템(GPS) 자산추적장치를 부착하여 실시간으로 차량과 자산의 정확한 위치를 알리는것이 가능함.\n    보다 자세한 정보는 : https://www.thingtech.com/wp-content/uploads/2018/04/ThingTech-Construction-Case-Study-AS.pdf",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 86,
          "S_NAME": "Tive",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "실시간 배송 위치 및 상태 추적 클라우드 솔루션",
          "S_EMPLOYEE_NUM": "31명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "Komoni(CEO)에 따르면, Alpine Fresh, Crane Worldwide Logistics, Fastly, Aviagen, Hellman Logistics, BOA Logistics 등의 고객의 주도하에 올해 매출이 570% 증가했다고함.\n    로스앤젤레스에 본사를 둔 BOA Logistics는 국내 도로 교통, 철도, 항공 및 해상 화물 서비스를 제공하며 특히, Trader Joes, Kroger, Costco, Safeway 및 Sysco Foods와 같은 주요 식료품 및 식품 브랜드의 물류를 냉장 트럭 운송, 창고 및 저온 보관, 배수 및 항만 픽업, 대량 및 트럭 적재 파트너, 철도 서비스 등을  활용하여 전국의 목표 위치로 배송함.\n\n    Tive는 이러한 BOA에 Tive 소프트웨어 플랫폼 제공하여 아웃소싱 업체를 면밀히 모니터링할 수 있는 기회를 제공하여 다음과 같은 사항을 쉽게 확인할 수 있도 돕고있음\n    - 냉장 장치 온도 및 습도\n    - 선적 위치 출처\n    - 트럭 정지 지연 또는 긴 휴식 시간\n    - 현장 배송시간 확인\n    - 동적 배송 경로 결정(기상 데이터와 Tive 온도 및 GPS 데이터와 페어링을 기반)\n    - 광감각",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2021 DFS"
        },
        {
          "S_NO": 87,
          "S_NAME": "WISER Systems",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "기업의 중요 자산 추적 솔루션",
          "S_EMPLOYEE_NUM": "10명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS / 2021 후보"
        },
        {
          "S_NO": 88,
          "S_NAME": "IAM Robotics",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "물류센터 픽업/분류 등 로봇팔 제작",
          "S_EMPLOYEE_NUM": "6명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "- Flash : 바코드, 크기 및 무게, 박스 내부 제품의 고해상도 이미지 출력\n    - Swift : 장애물 감지 기술을 통해 창고 내부를 이동하며 포장 및 배송 작업 수행\n    - Swiftlink : 창고관리시스템과 통합하여 창고 내 실시간 Swift 차량 관리",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 89,
          "S_NAME": "Berkshire Grey",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "물류센터 픽업/분류 등 로봇 제작",
          "S_EMPLOYEE_NUM": "117명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "- 상하차 시스템, 물체 더미에서 꺼내 분류하는 시스템\n    - MARS(Massive autonomous robot sorting : 모바일 로봇 시스템)",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 90,
          "S_NAME": "Grabit",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "물류센터 로봇 및 컨베이어 제작",
          "S_EMPLOYEE_NUM": "45명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 91,
          "S_NAME": "Vecna Robotics",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "물류센터내 상품 분류/운송 로봇",
          "S_EMPLOYEE_NUM": "90명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "- 자재 처리 등 물류 작업에 활용할 수 있는 자율이동 로봇 및 로봇 관리 소프트웨어 플랫폼 개발, 공급\n    - 실시간으로 작업의 배분, 작업 흐름의 처리, 작업자와 로봇 간 정보 공유가 가능한 로봇 관리 소프트웨어 플랫폼",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 92,
          "S_NAME": "Fetch Robotics",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "물류센터내 상품 분류/운송 로봇",
          "S_EMPLOYEE_NUM": "135명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "- 주문 접수 시 창고에서 물건을 바구니에 넣는 피킹로봇 (Fetch)\n    - 포장대까지 운반하는 이송로봇 (Freight)\n    - 로봇 관리용 소프트웨어 (Fetchcore) ",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 93,
          "S_NAME": "Seegrid",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "물류센터내 비전인식 자율주행 로봇",
          "S_EMPLOYEE_NUM": "135명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "-  VGV(Vision Guided Vehicles, 자동운반차량)를 통해 물류창고 자동화 및 물류 작업 효율성 제고\n    - 창고 내 모든 VGV 정보 모니터링 지원",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 94,
          "S_NAME": "Locus Robotics",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "물류센터내 상품 분류/운송 로봇",
          "S_EMPLOYEE_NUM": "비공개",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 95,
          "S_NAME": "ATTAbotics",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "로보틱스",
          "S_MAIN_SERVICE": "풀필먼트 창고 설계, 제조, 설치",
          "S_EMPLOYEE_NUM": "198명",
          "S_LOCATION": "캐나다",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 96,
          "S_NAME": "LogiNext",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "모빌리티",
          "S_MAIN_SERVICE": "실시간 최적화 배송경로 제공",
          "S_EMPLOYEE_NUM": "100명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "- 차량, 인력 등 위치정보 실시간 추적을 통해 배송경로 시각화 및 최적화, 고객과 배송차량 위치에 따라 자동 배송 할당, POS의 현금, 카드 관리 툴 제공\n    - 조건 변경에 따른 재 라우팅, 예상도착시간 실시간 업데이트 기능",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 97,
          "S_NAME": "Wise Systems",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "모빌리티",
          "S_MAIN_SERVICE": "실시간 최적화 배송경로 제공",
          "S_EMPLOYEE_NUM": "30명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "- 배송경로 실시간 최적화, 배송상태 실시간 알림기능 제공\n    - 기계학습 알고리즘을 통해 라우팅 성능과 정확성 향상",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 98,
          "S_NAME": "Scandit",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "스캐닝, 문자인식 소프트웨어(모바일)",
          "S_EMPLOYEE_NUM": "110명",
          "S_LOCATION": "스위스",
          "S_SERVICE_DETL": "- 고성능 바코드 스캐닝 소프트웨어를 모바일 장치(스마트폰)에 연결, 바코드 스캐닝, 여권/ID카드 등 문자인식\n    - 윈도우, iOS, Android 등 다양한 운영체제에서 작동\n    - 한 번에 여러 바코드 추적 및 디코딩 가능",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 99,
          "S_NAME": "AVRL",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "자연언어(음성) 인식 플랫폼 제공",
          "S_EMPLOYEE_NUM": "20명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 100,
          "S_NAME": "Datch",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "음성인식 기능을 사내 시스템에 연결",
          "S_EMPLOYEE_NUM": "3명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 101,
          "S_NAME": "Fero Ai",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "음성인식 지능형 물류관리 플랫폼",
          "S_EMPLOYEE_NUM": "25명",
          "S_LOCATION": "UAE",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 102,
          "S_NAME": "Froglabs",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "AI",
          "S_MAIN_SERVICE": "AI를 통해 날씨정보를 공급망에 적용",
          "S_EMPLOYEE_NUM": "4명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 103,
          "S_NAME": "OneClick",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "AI",
          "S_MAIN_SERVICE": "AI 프로그램 구축 플랫폼 제공",
          "S_EMPLOYEE_NUM": "8명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 104,
          "S_NAME": "RealityEngines",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "AI, 딥러닝 활용 Data 분석/수요예측",
          "S_EMPLOYEE_NUM": "20명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "- 재고관리 등 고객사, 벤더의 수요를 정확하게 예측할 수 있는 서비스 제공\n    - 불안전하고 History가 적은 Data를 통해서도 정확한 예측 가능\n    - 사용자가 머신러닝에 대한 전문지식이 없어도 사용가능한 서비스",
          "S_SPECIAL_FEATURE": "Abacus사로 이름 변경됨",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 105,
          "S_NAME": "Prevedere",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "산업(소비재, 소매, 여행 등) 예측",
          "S_EMPLOYEE_NUM": "63명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 106,
          "S_NAME": "OpenLegacy",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "API 등 데이터 접근/처리 서비스",
          "S_EMPLOYEE_NUM": "120명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 107,
          "S_NAME": "RapidAPI",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "API Marketplace (공용 API 연결)",
          "S_EMPLOYEE_NUM": "50명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 108,
          "S_NAME": "Withlocals",
          "S_CATEGORY": "IT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "현지인이 직접 판매 가능한 여행 상품 P2P 마켓 플랫폼",
          "S_EMPLOYEE_NUM": "100명",
          "S_LOCATION": "네덜란드",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 109,
          "S_NAME": "Axway",
          "S_CATEGORY": "IT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "다중 엔터프라이즈 클라우드 통합, API 및 ID 관리 소프트웨어",
          "S_EMPLOYEE_NUM": "5000명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 110,
          "S_NAME": "IndoorAtlas",
          "S_CATEGORY": "IT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "전세계를 대상으로 실내 위치 정보를 기반으로 애플리케이션개발이 가능하도록 하는 솔루션",
          "S_EMPLOYEE_NUM": "17명",
          "S_LOCATION": "핀란드",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 111,
          "S_NAME": "AntWorks",
          "S_CATEGORY": "IT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "비정형 문서 분류, 데이터 분석, 업무 규칙 적용 을 통해 전사적인 업무 디지털화를 가능하게 하는 솔루션",
          "S_EMPLOYEE_NUM": "500명",
          "S_LOCATION": "싱가포르",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 112,
          "S_NAME": "nFlux",
          "S_CATEGORY": "IT",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "영상 분석 플랫폼 서비스",
          "S_EMPLOYEE_NUM": "15명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 113,
          "S_NAME": "Unbabel",
          "S_CATEGORY": "IT",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "다국어 지원 서비스",
          "S_EMPLOYEE_NUM": "250",
          "S_LOCATION": "포르투갈",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 114,
          "S_NAME": "Smartling",
          "S_CATEGORY": "IT",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "컨텐츠 생성 플렛폼 서비스",
          "S_EMPLOYEE_NUM": "250명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 115,
          "S_NAME": "Swarm Logistics",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "분산형 자율물류기구(DALO) 시스템을 통한 물류 체계화 솔루션",
          "S_EMPLOYEE_NUM": "2명",
          "S_LOCATION": "독일",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 116,
          "S_NAME": "FleetUp",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "Fleet Management, 360 Online Dashcam, 모바일 인력 관리, 자산 추적, ELD 준수 및 연료 폐기물 분석등이 가능한 올인원 솔루션",
          "S_EMPLOYEE_NUM": "80명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 117,
          "S_NAME": "KeepTruckin",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "트럭 운송 관리 플랙폼",
          "S_EMPLOYEE_NUM": "501 ~ 1000명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 118,
          "S_NAME": "FourKites",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "데이터 분석",
          "S_MAIN_SERVICE": "머신러닝기반을 통한 글로벌 공급망 최적화 및 사업 통찰력 제공",
          "S_EMPLOYEE_NUM": "480명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 119,
          "S_NAME": "FarEye",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "모빌리티, 데이터 분석, 자동화를 활용한 신속, 정확한 물류의 이동을 위한 SaaS 플랫폼",
          "S_EMPLOYEE_NUM": "200명",
          "S_LOCATION": "인도",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 120,
          "S_NAME": "Turvo",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "실시간 협업 물류 플랫폼",
          "S_EMPLOYEE_NUM": "50명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 121,
          "S_NAME": "Shipamax",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "공급망 가속화를 위한 RPA기반의 데이터 추출 시스템",
          "S_EMPLOYEE_NUM": "10명",
          "S_LOCATION": "영국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 122,
          "S_NAME": "RPA Labs",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "공급망 / 물류 산업 비즈니스 프로세스 자동화를 위한 RPA 솔루션",
          "S_EMPLOYEE_NUM": "10명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 123,
          "S_NAME": "Automation Anywhere",
          "S_CATEGORY": "물류",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "엔터프라이즈급 인지형 RPA 플랫폼",
          "S_EMPLOYEE_NUM": "1000명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 124,
          "S_NAME": "360 Stories",
          "S_CATEGORY": "여행",
          "S_TECH_TYPE": "VR",
          "S_MAIN_SERVICE": "AR/VR과 같은 새로운 몰입형 세일즈 체널에서 소비될 수 있는 컨텐츠 제작 솔루션",
          "S_EMPLOYEE_NUM": "20명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 125,
          "S_NAME": "Inflight VR",
          "S_CATEGORY": "여행",
          "S_TECH_TYPE": "VR",
          "S_MAIN_SERVICE": "여행산업에서 활용 될 수 있는 VR 환경 제공",
          "S_EMPLOYEE_NUM": "25명",
          "S_LOCATION": "독일",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 126,
          "S_NAME": "SkyLights",
          "S_CATEGORY": "여행",
          "S_TECH_TYPE": "VR",
          "S_MAIN_SERVICE": "비행기 내에서 시청 가능한 VR 시청각 컨텐츠",
          "S_EMPLOYEE_NUM": "비공개",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 127,
          "S_NAME": "Port",
          "S_CATEGORY": "여행",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "온디맨드 방식의 예약 플랫폼 및 상호작용가능한 화상연결을 통한 여행지 관광 및 이벤트 참여 솔루션",
          "S_EMPLOYEE_NUM": "3명",
          "S_LOCATION": "싱가포르",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 128,
          "S_NAME": "BB-Trip",
          "S_CATEGORY": "여행",
          "S_TECH_TYPE": "모빌리티",
          "S_MAIN_SERVICE": "공항 셔틀 서비스",
          "S_EMPLOYEE_NUM": "비공개",
          "S_LOCATION": "일본",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 129,
          "S_NAME": "Heycars",
          "S_CATEGORY": "여행",
          "S_TECH_TYPE": "모빌리티",
          "S_MAIN_SERVICE": "전 세계적으로 가장 집약적인 대응범위를 갖춘 자동차 서비스 플랫폼",
          "S_EMPLOYEE_NUM": "80명",
          "S_LOCATION": "중국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 130,
          "S_NAME": "Welcome Pickups",
          "S_CATEGORY": "여행",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "A 지점과 B 지점 간 공항 환승에 대한 상품화된 서비스 제공을 통해 맞춤형 여행 경험을 제공",
          "S_EMPLOYEE_NUM": "105명",
          "S_LOCATION": "영국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 131,
          "S_NAME": "Servantrip",
          "S_CATEGORY": "여행",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "전세계에서 모든 전송 서비스 및 시간대 별 운전 기사 예약등이 가능한 B2B 플랫폼",
          "S_EMPLOYEE_NUM": "50명",
          "S_LOCATION": "스페인",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 132,
          "S_NAME": "Mozio",
          "S_CATEGORY": "여행",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "공항 운송 수단 검색 및 예약 솔루션",
          "S_EMPLOYEE_NUM": "80명",
          "S_LOCATION": "미국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 133,
          "S_NAME": "Petner",
          "S_CATEGORY": "여행",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "여행객들을 대상으로 반려견을 맡길 수 있는 전문가들을 연결해주는 솔루션",
          "S_EMPLOYEE_NUM": "비공개",
          "S_LOCATION": "대한민국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        },
        {
          "S_NO": 134,
          "S_NAME": "Wayo",
          "S_CATEGORY": "여행",
          "S_TECH_TYPE": "플랫폼 서비스",
          "S_MAIN_SERVICE": "펫시터 서비스",
          "S_EMPLOYEE_NUM": "비공개",
          "S_LOCATION": "대한민국",
          "S_SERVICE_DETL": "",
          "S_SPECIAL_FEATURE": "",
          "S_RESEARCHED_TIME": "2020 DFS"
        }
      ];